Kafka with Strimzi (on Kubernetes
adrianryt/SUU_AGH pull request #3
Opened 2023-03-26 22:34 UTC by xsanm

1. Creating and Deploying a Strimzi Kafka Cluster
2. Creating Producer and Consumer apps using Go and Scala and deploying on Kubernetes
3. Monitoring our Strimzi Kafka Cluster with Prometheus and Grafana

2023-03-26 22:35 UTC, DawidGrapa commented
Missing bracket in PR name ...

2023-03-26 22:35 UTC, xsanm commented
> Missing bracket in PR name ...

fixed :)

2023-03-26 22:36 UTC, DawidGrapa approved these changes

2023-03-26 22:36 UTC, DawidGrapa commented on resources/kafka-metrics.yaml
> +      timeoutSeconds: 5
why not 4.99 s? performance would be better

2023-03-26 22:36 UTC, DawidGrapa commented on resources/kafka-metrics.yaml
> +      type: GAUGE
GUAG

2023-03-26 22:36 UTC, DawidGrapa commented on resources/kafka-persistent.yaml
> +        size: 100Gi
man I do not have such space

2023-03-26 22:36 UTC, DawidGrapa commented on resources/prometheus-rules.yaml
> +      for: 10s
why 10?

2023-03-26 22:37 UTC, adrianryt commented
🤯

2023-03-26 22:39 UTC, xsanm commented
@Atheam what do you think, Doug? 😳

2023-03-26 22:42 UTC, Atheam commented
LGTM 👍

2023-03-26 23:08 UTC, wawel37 commented
Dobrze chłopaki robią, pozdro legnica

2023-03-26 23:08 UTC, wawel37 commented
Zydzi

2023-03-27 13:43 UTC, Akatroj requested changes

2023-03-27 13:43 UTC, Akatroj commented on resources/kafka-metrics.yaml
> +    # Ex) kafka.server<type=(KafkaRequestHandlerPool), name=(RequestHandlerAvgIdlePercent)><>MeanRate
```suggestion
    # Sex) kafka.server<type=(KafkaRequestHandlerPool), name=(RequestHandlerAvgIdlePercent)><>MeanRate
```

2023-03-28 20:08 UTC, merged